name: CI/CD python count app 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-test-push:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push prod image
      - name: build docker image
        run: |
          docker build -t numanh14/cicd-task-1:latest .
          docker push numanh14/cicd-task-1:latest 

      

        